"""
Telegram Setup Script — Elite v3.1
====================================
Interactive script to securely configure Telegram notifications.
Saves credentials to .env file (NOT in source code).

Usage:
    python setup_telegram.py
"""

import os
import sys


def print_banner():
    print("\n" + "=" * 60)
    print("  🤖 ELITE BOT — Telegram Notification Setup")
    print("=" * 60)


def print_instructions():
    print("""
  📋 INSTRUCTIONS:
  ─────────────────────────────────────────────────────
  1. Open Telegram and search for @BotFather
  2. Send /newbot and follow the prompts
  3. Copy the Bot Token (looks like: 123456:ABC-DEF...)
  4. Create a group/channel or use your personal chat
  5. Add the bot to the group
  6. To get your Chat ID:
     a. Send any message to the bot/group
     b. Visit: https://api.telegram.org/bot<YOUR_TOKEN>/getUpdates
     c. Look for "chat":{"id": YOUR_CHAT_ID}
  ─────────────────────────────────────────────────────
    """)


def validate_token(token):
    """Basic validation for Telegram bot token format."""
    if not token or ":" not in token:
        return False
    parts = token.split(":")
    if len(parts) != 2:
        return False
    try:
        int(parts[0])
    except ValueError:
        return False
    return len(parts[1]) > 10


def validate_chat_id(chat_id):
    """Validate chat ID (integer, can be negative for groups)."""
    try:
        int(chat_id)
        return True
    except ValueError:
        return False


def test_connection(token, chat_id):
    """Send a test message to verify the setup works."""
    try:
        import requests
        url = f"https://api.telegram.org/bot{token}/sendMessage"
        payload = {
            "chat_id": chat_id,
            "text": "✅ *Elite Trading Bot v3.1*\n\n🔗 Telegram connection successful!\n📊 You will receive trade alerts and daily summaries here.",
            "parse_mode": "Markdown",
        }
        response = requests.post(url, json=payload, timeout=10)
        data = response.json()

        if data.get("ok"):
            print("\n  ✅ TEST MESSAGE SENT SUCCESSFULLY!")
            print("  Check your Telegram — you should see a confirmation message.\n")
            return True
        else:
            print(f"\n  ❌ Telegram API Error: {data.get('description', 'Unknown error')}")
            return False
    except ImportError:
        print("\n  ⚠️  'requests' library not installed. Run: pip install requests")
        print("  Skipping test. Credentials saved anyway.")
        return True
    except Exception as e:
        print(f"\n  ❌ Connection test failed: {e}")
        return False


def save_env_file(token, chat_id, env_path=".env"):
    """Write credentials to .env file."""
    with open(env_path, "w") as f:
        f.write("# Elite Trading Bot — Telegram Credentials\n")
        f.write("# Generated by setup_telegram.py\n")
        f.write(f"TELEGRAM_BOT_TOKEN={token}\n")
        f.write(f"TELEGRAM_CHAT_ID={chat_id}\n")

    print(f"\n  💾 Credentials saved to: {os.path.abspath(env_path)}")
    print("  🔒 This file is NOT committed to source control.")

    # Create/update .gitignore
    gitignore_path = os.path.join(os.path.dirname(env_path), ".gitignore")
    gitignore_entries = [".env", "*.log", "active_trades.json", "__pycache__/"]

    existing = set()
    if os.path.exists(gitignore_path):
        with open(gitignore_path, "r") as f:
            existing = set(line.strip() for line in f.readlines())

    new_entries = [e for e in gitignore_entries if e not in existing]
    if new_entries:
        with open(gitignore_path, "a") as f:
            for entry in new_entries:
                f.write(f"\n{entry}")
        print(f"  📝 Updated .gitignore with: {', '.join(new_entries)}")


def main():
    print_banner()
    print_instructions()

    # --- Bot Token ---
    while True:
        token = input("  🔑 Paste your Bot Token: ").strip()
        if validate_token(token):
            print("  ✅ Token format looks good!")
            break
        else:
            print("  ❌ Invalid token format. Should look like: 123456789:ABCDefGHI-jklMNO...")

    # --- Chat ID ---
    while True:
        chat_id = input("  💬 Paste your Chat ID: ").strip()
        if validate_chat_id(chat_id):
            print("  ✅ Chat ID accepted!")
            break
        else:
            print("  ❌ Invalid Chat ID. Should be a number (negative for groups).")

    # --- Save ---
    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
    save_env_file(token, chat_id, env_path)

    # --- Test ---
    print("\n  📡 Testing connection...")
    success = test_connection(token, chat_id)

    if success:
        print("  ─────────────────────────────────────────────────────")
        print("  🎉 SETUP COMPLETE!")
        print("  ")
        print("  Next steps:")
        print("  1. Set TELEGRAM_ENABLED = True in config.py")
        print("  2. Run: python main.py")
        print("  3. Watch your Telegram for live trade alerts! 📲")
        print("  ─────────────────────────────────────────────────────\n")
    else:
        print("  ⚠️  Credentials saved but test failed.")
        print("  Double-check your token and chat ID, then run this script again.\n")


if __name__ == "__main__":
    main()
